os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
git:
  depth: 3
env:
  - FLUTTER_VERSION=stable
  - FLUTTER_VERSION=beta
before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION ~/flutter
  - ~/flutter/bin/flutter doctor
script:
  - ~/flutter/bin/cache/dart-sdk/bin/dartfmt --set-exit-if-changed -n .
#  - ~/flutter/bin/flutter packages get && ~/flutter/bin/cache/dart-sdk/bin/dartanalyzer .
  - ~/flutter/bin/flutter test
cache:
  directories:
    - $HOME/shared/.pub-cache

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]