name: simple_map
description: A Flutter plugin for displaying a simple flat world map with animated points.
version: 0.0.2
homepage: 'https://github.com/tiamo/flutter-simple-map'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
